# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Gzone_App' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Gzone_App
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'
 pod 'XLPagerTabStrip', '~> 7.0'
 pod 'ReachabilitySwift', '~> 3'
 target 'Gzone_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
